BEGIN;

WITH seed("key", en, zh, hi, es, ca, ar, fr, de, pt, ru, it) AS (
  VALUES
    ('auth.common.verify_email_required', 'Please verify your email before accessing the builder. Check your inbox for the confirmation link.', '请在访问编辑器前验证您的电子邮件。请检查收件箱中的确认链接。', 'बिल्डर में जाने से पहले कृपया अपना ईमेल सत्यापित करें। पुष्टि लिंक के लिए अपना इनबॉक्स देखें।', 'Verifica tu correo antes de acceder al editor. Revisa tu bandeja de entrada para el enlace de confirmacion.', 'Verifica el teu correu abans d''accedir al builder. Revisa la safata d''entrada per a l''enllac de confirmacio.', 'يرجى التحقق من بريدك الإلكتروني قبل الدخول إلى المنشئ. تحقق من صندوق الوارد لرابط التأكيد.', 'Veuillez verifier votre e-mail avant d''acceder au builder. Verifiez votre boite de reception pour le lien de confirmation.', 'Bitte bestaetige deine E-Mail, bevor du auf den Builder zugreifst. Pruefe deinen Posteingang auf den Bestaetigungslink.', 'Verifique seu e-mail antes de acessar o builder. Confira sua caixa de entrada para o link de confirmacao.', 'Пожалуйста, подтвердите e-mail перед входом в конструктор. Проверьте входящие для ссылки подтверждения.', 'Verifica la tua email prima di accedere al builder. Controlla la posta in arrivo per il link di conferma.'),

    ('auth.common.email_invalid', 'Please enter a valid email address.', '请输入有效的电子邮件地址。', 'कृपया एक मान्य ईमेल पता दर्ज करें।', 'Introduce una direccion de correo valida.', 'Introdueix una adreca de correu valida.', 'يرجى إدخال عنوان بريد إلكتروني صالح.', 'Veuillez saisir une adresse e-mail valide.', 'Bitte gib eine gueltige E-Mail-Adresse ein.', 'Digite um endereco de e-mail valido.', 'Введите корректный адрес e-mail.', 'Inserisci un indirizzo email valido.'),
    ('auth.common.password_min_length', 'Password must be at least 8 characters long.', '密码长度至少为8个字符。', 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।', 'La contrasena debe tener al menos 8 caracteres.', 'La contrasenya ha de tenir almenys 8 caracters.', 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.', 'Le mot de passe doit contenir au moins 8 caracteres.', 'Das Passwort muss mindestens 8 Zeichen lang sein.', 'A senha deve ter pelo menos 8 caracteres.', 'Пароль должен содержать не менее 8 символов.', 'La password deve contenere almeno 8 caratteri.'),
    ('auth.common.passwords_do_not_match', 'Passwords do not match.', '两次输入的密码不一致。', 'पासवर्ड मेल नहीं खाते।', 'Las contrasenas no coinciden.', 'Les contrasenyes no coincideixen.', 'كلمتا المرور غير متطابقتين.', 'Les mots de passe ne correspondent pas.', 'Die Passwoerter stimmen nicht ueberein.', 'As senhas nao coincidem.', 'Пароли не совпадают.', 'Le password non coincidono.'),
    ('auth.common.unexpected_error', 'An unexpected error occurred. Please try again.', '发生意外错误。请重试。', 'एक अप्रत्याशित त्रुटि हुई। कृपया फिर से प्रयास करें।', 'Ocurrio un error inesperado. Intentalo de nuevo.', 'S''ha produït un error inesperat. Torna-ho a provar.', 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.', 'Une erreur inattendue est survenue. Veuillez reessayer.', 'Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut.', 'Ocorreu um erro inesperado. Tente novamente.', 'Произошла непредвиденная ошибка. Пожалуйста, попробуйте снова.', 'Si e verificato un errore imprevisto. Riprova.'),
    ('auth.common.check_email', 'Check Your Email', '检查你的邮箱', 'अपना ईमेल जांचें', 'Revisa tu correo', 'Revisa el teu correu', 'تحقق من بريدك الإلكتروني', 'Verifiez votre e-mail', 'Pruefe deine E-Mails', 'Verifique seu e-mail', 'Проверьте вашу почту', 'Controlla la tua email'),
    ('auth.common.return_to_login', 'Return to Login', '返回登录', 'लॉगिन पर वापस जाएं', 'Volver a iniciar sesion', 'Torna a iniciar sessio', 'العودة إلى تسجيل الدخول', 'Retour a la connexion', 'Zurueck zum Login', 'Voltar ao login', 'Вернуться ко входу', 'Torna al login'),
    ('auth.common.email', 'Email', '电子邮件', 'ईमेल', 'Correo electronico', 'Correu electronic', 'البريد الإلكتروني', 'E-mail', 'E-Mail', 'E-mail', 'Электронная почта', 'Email'),
    ('auth.common.email_placeholder', 'Enter your email', '输入你的电子邮件', 'अपना ईमेल दर्ज करें', 'Introduce tu correo', 'Introdueix el teu correu', 'ادخل بريدك الإلكتروني', 'Saisissez votre e-mail', 'Gib deine E-Mail ein', 'Digite seu e-mail', 'Введите ваш e-mail', 'Inserisci la tua email'),
    ('auth.common.password', 'Password', '密码', 'पासवर्ड', 'Contrasena', 'Contrasenya', 'كلمة المرور', 'Mot de passe', 'Passwort', 'Senha', 'Пароль', 'Password'),
    ('auth.common.sign_up', 'Sign Up', '注册', 'साइन अप करें', 'Registrarse', 'Registra''t', 'إنشاء حساب', 'S''inscrire', 'Registrieren', 'Cadastrar', 'Зарегистрироваться', 'Registrati'),
    ('auth.common.log_in', 'Log in', '登录', 'लॉग इन', 'Iniciar sesion', 'Inicia sessio', 'تسجيل الدخول', 'Se connecter', 'Anmelden', 'Entrar', 'Войти', 'Accedi'),
    ('auth.common.verification_sent', 'Verification email sent. Please check your inbox.', '验证邮件已发送。请检查你的收件箱。', 'सत्यापन ईमेल भेज दिया गया है। कृपया अपना इनबॉक्स जांचें।', 'Correo de verificacion enviado. Revisa tu bandeja de entrada.', 'Correu de verificacio enviat. Revisa la teva safata d''entrada.', 'تم إرسال بريد التحقق. يرجى التحقق من صندوق الوارد.', 'E-mail de verification envoye. Veuillez verifier votre boite de reception.', 'Bestaetigungs-E-Mail wurde gesendet. Bitte pruefe deinen Posteingang.', 'E-mail de verificacao enviado. Verifique sua caixa de entrada.', 'Письмо для подтверждения отправлено. Проверьте входящие.', 'Email di verifica inviata. Controlla la posta in arrivo.'),
    ('auth.common.verification_resend_failed', 'Could not resend verification email. Please try again.', '无法重新发送验证邮件。请重试。', 'सत्यापन ईमेल दोबारा नहीं भेजा जा सका। कृपया फिर प्रयास करें।', 'No se pudo reenviar el correo de verificacion. Intentalo de nuevo.', 'No s''ha pogut reenviar el correu de verificacio. Torna-ho a provar.', 'تعذر إعادة إرسال بريد التحقق. يرجى المحاولة مرة أخرى.', 'Impossible de renvoyer l''e-mail de verification. Veuillez reessayer.', 'Die Bestaetigungs-E-Mail konnte nicht erneut gesendet werden. Bitte versuche es erneut.', 'Nao foi possivel reenviar o e-mail de verificacao. Tente novamente.', 'Не удалось повторно отправить письмо подтверждения. Пожалуйста, попробуйте снова.', 'Impossibile reinviare l''email di verifica. Riprova.'),
    ('auth.common.password_required', 'Password is required.', '密码是必填项。', 'पासवर्ड आवश्यक है।', 'La contrasena es obligatoria.', 'La contrasenya es obligatoria.', 'كلمة المرور مطلوبة.', 'Le mot de passe est requis.', 'Passwort ist erforderlich.', 'A senha e obrigatoria.', 'Требуется пароль.', 'La password e obbligatoria.'),
    ('auth.common.resending_verification', 'Resending verification...', '正在重新发送验证...', 'सत्यापन पुनः भेजा जा रहा है...', 'Reenviando verificacion...', 'Reenviant verificacio...', 'جارٍ إعادة إرسال التحقق...', 'Renvoi de la verification...', 'Bestaetigung wird erneut gesendet...', 'Reenviando verificacao...', 'Повторная отправка подтверждения...', 'Invio della verifica in corso...'),
    ('auth.common.resend_verification', 'Resend verification email', '重新发送验证邮件', 'सत्यापन ईमेल फिर से भेजें', 'Reenviar correo de verificacion', 'Reenvia el correu de verificacio', 'إعادة إرسال بريد التحقق', 'Renvoyer l''e-mail de verification', 'Bestaetigungs-E-Mail erneut senden', 'Reenviar e-mail de verificacao', 'Отправить письмо подтверждения повторно', 'Reinvia email di verifica'),

    ('auth.signup.page_title', 'Sign Up | WeddWeb', '注册 | WeddWeb', 'साइन अप | WeddWeb', 'Registro | WeddWeb', 'Registre | WeddWeb', 'التسجيل | WeddWeb', 'Inscription | WeddWeb', 'Registrierung | WeddWeb', 'Cadastro | WeddWeb', 'Регистрация | WeddWeb', 'Registrazione | WeddWeb'),
    ('auth.signup.page_description', 'Create your wedding website account', '创建你的婚礼网站账户', 'अपनी शादी वेबसाइट का खाता बनाएं', 'Crea tu cuenta para tu web de boda', 'Crea el teu compte del web de casament', 'أنشئ حساب موقع زفافك', 'Creez votre compte pour votre site de mariage', 'Erstelle dein Konto fuer deine Hochzeitswebsite', 'Crie sua conta para o site do casamento', 'Создайте аккаунт для свадебного сайта', 'Crea il tuo account per il sito di matrimonio'),
    ('auth.signup.title', 'Create Your Account', '创建你的账户', 'अपना खाता बनाएं', 'Crea tu cuenta', 'Crea el teu compte', 'أنشئ حسابك', 'Creez votre compte', 'Erstelle dein Konto', 'Crie sua conta', 'Создайте аккаунт', 'Crea il tuo account'),
    ('auth.signup.success_message', 'We have sent you a verification link. Please check your email and click the link to activate your account.', '我们已向你发送验证链接。请检查邮箱并点击链接激活账户。', 'हमने आपको एक सत्यापन लिंक भेजा है। कृपया अपना ईमेल जांचें और खाते को सक्रिय करने के लिए लिंक पर क्लिक करें।', 'Te hemos enviado un enlace de verificacion. Revisa tu correo y haz clic en el enlace para activar tu cuenta.', 'T''hem enviat un enllac de verificacio. Revisa el teu correu i fes clic a l''enllac per activar el compte.', 'لقد أرسلنا لك رابط تحقق. يرجى التحقق من بريدك الإلكتروني والضغط على الرابط لتفعيل حسابك.', 'Nous vous avons envoye un lien de verification. Verifiez votre e-mail et cliquez sur le lien pour activer votre compte.', 'Wir haben dir einen Bestaetigungslink gesendet. Bitte pruefe deine E-Mails und klicke auf den Link, um dein Konto zu aktivieren.', 'Enviamos um link de verificacao. Verifique seu e-mail e clique no link para ativar sua conta.', 'Мы отправили ссылку для подтверждения. Проверьте почту и перейдите по ссылке, чтобы активировать аккаунт.', 'Ti abbiamo inviato un link di verifica. Controlla la tua email e fai clic sul link per attivare l''account.'),
    ('auth.signup.full_name', 'Full Name', '姓名', 'पूरा नाम', 'Nombre completo', 'Nom complet', 'الاسم الكامل', 'Nom complet', 'Vollstaendiger Name', 'Nome completo', 'Полное имя', 'Nome completo'),
    ('auth.signup.optional', '(optional)', '(可选)', '(वैकल्पिक)', '(opcional)', '(opcional)', '(اختياري)', '(optionnel)', '(optional)', '(opcional)', '(необязательно)', '(facoltativo)'),
    ('auth.signup.full_name_placeholder', 'Enter your full name', '输入你的姓名', 'अपना पूरा नाम दर्ज करें', 'Introduce tu nombre completo', 'Introdueix el teu nom complet', 'ادخل اسمك الكامل', 'Saisissez votre nom complet', 'Gib deinen vollstaendigen Namen ein', 'Digite seu nome completo', 'Введите ваше полное имя', 'Inserisci il tuo nome completo'),
    ('auth.signup.password_placeholder', 'Enter your password (min 8 characters)', '输入你的密码（至少8个字符）', 'अपना पासवर्ड दर्ज करें (कम से कम 8 अक्षर)', 'Introduce tu contrasena (minimo 8 caracteres)', 'Introdueix la teva contrasenya (minim 8 caracters)', 'ادخل كلمة المرور (8 أحرف على الأقل)', 'Saisissez votre mot de passe (8 caracteres minimum)', 'Gib dein Passwort ein (mindestens 8 Zeichen)', 'Digite sua senha (minimo de 8 caracteres)', 'Введите пароль (минимум 8 символов)', 'Inserisci la password (minimo 8 caratteri)'),
    ('auth.signup.confirm_password', 'Confirm Password', '确认密码', 'पासवर्ड की पुष्टि करें', 'Confirmar contrasena', 'Confirma la contrasenya', 'تاكيد كلمة المرور', 'Confirmer le mot de passe', 'Passwort bestaetigen', 'Confirmar senha', 'Подтвердите пароль', 'Conferma password'),
    ('auth.signup.confirm_password_placeholder', 'Confirm your password', '确认你的密码', 'अपने पासवर्ड की पुष्टि करें', 'Confirma tu contrasena', 'Confirma la teva contrasenya', 'اكد كلمة المرور', 'Confirmez votre mot de passe', 'Bestaetige dein Passwort', 'Confirme sua senha', 'Подтвердите ваш пароль', 'Conferma la tua password'),
    ('auth.signup.submitting', 'Creating Account...', '正在创建账户...', 'खाता बनाया जा रहा है...', 'Creando cuenta...', 'Creant compte...', 'جارٍ إنشاء الحساب...', 'Creation du compte...', 'Konto wird erstellt...', 'Criando conta...', 'Создание аккаунта...', 'Creazione account...'),
    ('auth.signup.have_account', 'Already have an account?', '已经有账号？', 'क्या आपके पास पहले से खाता है?', 'Ya tienes una cuenta?', 'Ja tens un compte?', 'هل لديك حساب بالفعل؟', 'Vous avez deja un compte ?', 'Hast du bereits ein Konto?', 'Ja tem uma conta?', 'Уже есть аккаунт?', 'Hai gia un account?'),

    ('auth.login.page_title', 'Login | WeddWeb', '登录 | WeddWeb', 'लॉगिन | WeddWeb', 'Iniciar sesion | WeddWeb', 'Inicia sessio | WeddWeb', 'تسجيل الدخول | WeddWeb', 'Connexion | WeddWeb', 'Login | WeddWeb', 'Entrar | WeddWeb', 'Вход | WeddWeb', 'Accesso | WeddWeb'),
    ('auth.login.page_description', 'Login to your wedding website dashboard', '登录到你的婚礼网站控制台', 'अपनी शादी वेबसाइट डैशबोर्ड में लॉग इन करें', 'Inicia sesion en el panel de tu web de boda', 'Inicia sessio al tauler del teu web de casament', 'سجل الدخول إلى لوحة تحكم موقع الزفاف', 'Connectez-vous a votre tableau de bord de site de mariage', 'Melde dich bei deinem Hochzeitswebsite-Dashboard an', 'Entre no painel do seu site de casamento', 'Войдите в панель управления свадебным сайтом', 'Accedi alla dashboard del tuo sito di matrimonio'),
    ('auth.login.welcome_back', 'Welcome Back', '欢迎回来', 'वापसी पर स्वागत है', 'Bienvenido de nuevo', 'Benvingut de nou', 'مرحبا بعودتك', 'Bon retour', 'Willkommen zurueck', 'Bem-vindo de volta', 'С возвращением', 'Bentornato'),
    ('auth.login.title', 'Login to Your Account', '登录到你的账户', 'अपने खाते में लॉग इन करें', 'Inicia sesion en tu cuenta', 'Inicia sessio al teu compte', 'سجل الدخول إلى حسابك', 'Connectez-vous a votre compte', 'Melde dich bei deinem Konto an', 'Entre na sua conta', 'Войдите в аккаунт', 'Accedi al tuo account'),
    ('auth.login.enter_email_for_resend', 'Please enter your email above to resend verification.', '请先输入你的邮箱以重新发送验证邮件。', 'सत्यापन दोबारा भेजने के लिए ऊपर अपना ईमेल दर्ज करें।', 'Introduce tu correo arriba para reenviar la verificacion.', 'Introdueix el teu correu a dalt per reenviar la verificacio.', 'يرجى إدخال بريدك الإلكتروني أعلاه لإعادة إرسال التحقق.', 'Veuillez saisir votre e-mail ci-dessus pour renvoyer la verification.', 'Bitte gib oben deine E-Mail ein, um die Bestaetigung erneut zu senden.', 'Digite seu e-mail acima para reenviar a verificacao.', 'Введите e-mail выше, чтобы повторно отправить подтверждение.', 'Inserisci la tua email sopra per reinviare la verifica.'),
    ('auth.login.password_placeholder', 'Enter your password', '输入你的密码', 'अपना पासवर्ड दर्ज करें', 'Introduce tu contrasena', 'Introdueix la teva contrasenya', 'ادخل كلمة المرور', 'Saisissez votre mot de passe', 'Gib dein Passwort ein', 'Digite sua senha', 'Введите ваш пароль', 'Inserisci la tua password'),
    ('auth.login.forgot_password', 'Forgot password?', '忘记密码？', 'पासवर्ड भूल गए?', 'Has olvidado tu contrasena?', 'Has oblidat la contrasenya?', 'هل نسيت كلمة المرور؟', 'Mot de passe oublie ?', 'Passwort vergessen?', 'Esqueceu a senha?', 'Забыли пароль?', 'Password dimenticata?'),
    ('auth.login.submitting', 'Logging in...', '正在登录...', 'लॉग इन किया जा रहा है...', 'Iniciando sesion...', 'Iniciant sessio...', 'جارٍ تسجيل الدخول...', 'Connexion...', 'Anmeldung laeuft...', 'Entrando...', 'Выполняется вход...', 'Accesso in corso...'),
    ('auth.login.success_redirecting', 'Login successful! Redirecting...', '登录成功！正在跳转...', 'लॉगिन सफल! पुनर्निर्देशित किया जा रहा है...', 'Inicio de sesion correcto. Redirigiendo...', 'Inici de sessio correcte. Redirigint...', 'تم تسجيل الدخول بنجاح. جارٍ التحويل...', 'Connexion reussie. Redirection...', 'Login erfolgreich. Weiterleitung...', 'Login realizado com sucesso. Redirecionando...', 'Вход выполнен успешно. Перенаправление...', 'Accesso riuscito. Reindirizzamento...'),
    ('auth.login.no_account', 'Do not have an account?', '还没有账号？', 'क्या आपका खाता नहीं है?', 'No tienes cuenta?', 'No tens compte?', 'ليس لديك حساب؟', 'Vous n''avez pas de compte ?', 'Noch kein Konto?', 'Nao tem uma conta?', 'Нет аккаунта?', 'Non hai un account?'),

    ('auth.forgot.page_title', 'Forgot Password | WeddWeb', '忘记密码 | WeddWeb', 'पासवर्ड भूल गए | WeddWeb', 'Olvide mi contrasena | WeddWeb', 'He oblidat la contrasenya | WeddWeb', 'نسيت كلمة المرور | WeddWeb', 'Mot de passe oublie | WeddWeb', 'Passwort vergessen | WeddWeb', 'Esqueci minha senha | WeddWeb', 'Забыли пароль | WeddWeb', 'Password dimenticata | WeddWeb'),
    ('auth.forgot.page_description', 'Reset your password', '重置你的密码', 'अपना पासवर्ड रीसेट करें', 'Restablece tu contrasena', 'Restableix la teva contrasenya', 'اعد تعيين كلمة المرور', 'Reinitialisez votre mot de passe', 'Setze dein Passwort zurueck', 'Redefina sua senha', 'Сбросьте пароль', 'Reimposta la password'),
    ('auth.forgot.title', 'Reset Your Password', '重置你的密码', 'अपना पासवर्ड रीसेट करें', 'Restablece tu contrasena', 'Restableix la teva contrasenya', 'اعد تعيين كلمة المرور', 'Reinitialisez votre mot de passe', 'Setze dein Passwort zurueck', 'Redefina sua senha', 'Сбросьте пароль', 'Reimposta la password'),
    ('auth.forgot.success_message', 'We have sent you a password reset link. Please check your email and click the link to reset your password.', '我们已向你发送密码重置链接。请检查邮箱并点击链接重置密码。', 'हमने आपको पासवर्ड रीसेट लिंक भेजा है। कृपया ईमेल देखें और पासवर्ड रीसेट करने के लिए लिंक पर क्लिक करें।', 'Te hemos enviado un enlace para restablecer tu contrasena. Revisa tu correo y haz clic en el enlace.', 'T''hem enviat un enllac per restablir la contrasenya. Revisa el correu i fes clic a l''enllac.', 'لقد أرسلنا لك رابط إعادة تعيين كلمة المرور. يرجى التحقق من بريدك الإلكتروني والنقر على الرابط.', 'Nous vous avons envoye un lien de reinitialisation du mot de passe. Verifiez votre e-mail et cliquez sur le lien.', 'Wir haben dir einen Link zum Zuruecksetzen des Passworts gesendet. Bitte pruefe deine E-Mails und klicke auf den Link.', 'Enviamos um link para redefinir sua senha. Verifique seu e-mail e clique no link.', 'Мы отправили ссылку для сброса пароля. Проверьте почту и перейдите по ссылке.', 'Ti abbiamo inviato un link per reimpostare la password. Controlla la tua email e fai clic sul link.'),
    ('auth.forgot.submitting', 'Sending Reset Link...', '正在发送重置链接...', 'रीसेट लिंक भेजा जा रहा है...', 'Enviando enlace de restablecimiento...', 'Enviant enllac de restabliment...', 'جارٍ إرسال رابط إعادة التعيين...', 'Envoi du lien de reinitialisation...', 'Link zum Zuruecksetzen wird gesendet...', 'Enviando link de redefinicao...', 'Отправка ссылки для сброса...', 'Invio link di reimpostazione...'),
    ('auth.forgot.submit', 'Send Reset Link', '发送重置链接', 'रीसेट लिंक भेजें', 'Enviar enlace de restablecimiento', 'Envia enllac de restabliment', 'إرسال رابط إعادة التعيين', 'Envoyer le lien de reinitialisation', 'Link zum Zuruecksetzen senden', 'Enviar link de redefinicao', 'Отправить ссылку для сброса', 'Invia link di reimpostazione'),
    ('auth.forgot.remember_password', 'Remember your password?', '记得你的密码？', 'क्या आपको अपना पासवर्ड याद है?', 'Recuerdas tu contrasena?', 'Recordes la teva contrasenya?', 'هل تتذكر كلمة المرور؟', 'Vous vous souvenez de votre mot de passe ?', 'Erinnerst du dich an dein Passwort?', 'Lembrou sua senha?', 'Помните пароль?', 'Ricordi la password?'),

    ('auth.reset.page_title', 'Reset Password | WeddWeb', '重置密码 | WeddWeb', 'पासवर्ड रीसेट | WeddWeb', 'Restablecer contrasena | WeddWeb', 'Restablir contrasenya | WeddWeb', 'إعادة تعيين كلمة المرور | WeddWeb', 'Reinitialiser le mot de passe | WeddWeb', 'Passwort zuruecksetzen | WeddWeb', 'Redefinir senha | WeddWeb', 'Сброс пароля | WeddWeb', 'Reimposta password | WeddWeb'),
    ('auth.reset.page_description', 'Set your new password', '设置你的新密码', 'अपना नया पासवर्ड सेट करें', 'Define tu nueva contrasena', 'Defineix la teva nova contrasenya', 'قم بتعيين كلمة المرور الجديدة', 'Definissez votre nouveau mot de passe', 'Lege dein neues Passwort fest', 'Defina sua nova senha', 'Установите новый пароль', 'Imposta la tua nuova password'),
    ('auth.reset.title', 'Reset Your Password', '重置你的密码', 'अपना पासवर्ड रीसेट करें', 'Restablece tu contrasena', 'Restableix la teva contrasenya', 'اعد تعيين كلمة المرور', 'Reinitialisez votre mot de passe', 'Setze dein Passwort zurueck', 'Redefina sua senha', 'Сбросьте пароль', 'Reimposta la password'),
    ('auth.reset.success_title', 'Password Reset Successful', '密码重置成功', 'पासवर्ड सफलतापूर्वक रीसेट हुआ', 'Contrasena restablecida correctamente', 'Contrasenya restablerta correctament', 'تمت إعادة تعيين كلمة المرور بنجاح', 'Reinitialisation du mot de passe reussie', 'Passwort erfolgreich zurueckgesetzt', 'Senha redefinida com sucesso', 'Пароль успешно сброшен', 'Password reimpostata con successo'),
    ('auth.reset.success_message', 'Your password has been reset. Redirecting to login...', '你的密码已重置。正在跳转到登录...', 'आपका पासवर्ड रीसेट हो गया है। लॉगिन पर भेजा जा रहा है...', 'Tu contrasena se ha restablecido. Redirigiendo al inicio de sesion...', 'La teva contrasenya s''ha restablert. Redirigint a l''inici de sessio...', 'تمت إعادة تعيين كلمة المرور. جارٍ التحويل إلى تسجيل الدخول...', 'Votre mot de passe a ete reinitialise. Redirection vers la connexion...', 'Dein Passwort wurde zurueckgesetzt. Weiterleitung zum Login...', 'Sua senha foi redefinida. Redirecionando para o login...', 'Ваш пароль был сброшен. Перенаправление на страницу входа...', 'La tua password e stata reimpostata. Reindirizzamento al login...'),
    ('auth.reset.new_password', 'New Password', '新密码', 'नया पासवर्ड', 'Nueva contrasena', 'Nova contrasenya', 'كلمة مرور جديدة', 'Nouveau mot de passe', 'Neues Passwort', 'Nova senha', 'Новый пароль', 'Nuova password'),
    ('auth.reset.new_password_placeholder', 'Enter your new password (min 8 characters)', '输入新密码（至少8个字符）', 'अपना नया पासवर्ड दर्ज करें (कम से कम 8 अक्षर)', 'Introduce tu nueva contrasena (minimo 8 caracteres)', 'Introdueix la nova contrasenya (minim 8 caracters)', 'ادخل كلمة المرور الجديدة (8 أحرف على الأقل)', 'Saisissez votre nouveau mot de passe (8 caracteres minimum)', 'Gib dein neues Passwort ein (mindestens 8 Zeichen)', 'Digite sua nova senha (minimo de 8 caracteres)', 'Введите новый пароль (минимум 8 символов)', 'Inserisci la nuova password (minimo 8 caratteri)'),
    ('auth.reset.confirm_new_password', 'Confirm New Password', '确认新密码', 'नए पासवर्ड की पुष्टि करें', 'Confirmar nueva contrasena', 'Confirma la nova contrasenya', 'تاكيد كلمة المرور الجديدة', 'Confirmer le nouveau mot de passe', 'Neues Passwort bestaetigen', 'Confirmar nova senha', 'Подтвердите новый пароль', 'Conferma nuova password'),
    ('auth.reset.confirm_new_password_placeholder', 'Confirm your new password', '确认你的新密码', 'अपने नए पासवर्ड की पुष्टि करें', 'Confirma tu nueva contrasena', 'Confirma la teva nova contrasenya', 'اكد كلمة المرور الجديدة', 'Confirmez votre nouveau mot de passe', 'Bestaetige dein neues Passwort', 'Confirme sua nova senha', 'Подтвердите новый пароль', 'Conferma la nuova password'),
    ('auth.reset.submitting', 'Resetting Password...', '正在重置密码...', 'पासवर्ड रीसेट किया जा रहा है...', 'Restableciendo contrasena...', 'Restablint contrasenya...', 'جارٍ إعادة تعيين كلمة المرور...', 'Reinitialisation du mot de passe...', 'Passwort wird zurueckgesetzt...', 'Redefinindo senha...', 'Сброс пароля...', 'Reimpostazione password...'),
    ('auth.reset.submit', 'Reset Password', '重置密码', 'पासवर्ड रीसेट करें', 'Restablecer contrasena', 'Restablir contrasenya', 'إعادة تعيين كلمة المرور', 'Reinitialiser le mot de passe', 'Passwort zuruecksetzen', 'Redefinir senha', 'Сбросить пароль', 'Reimposta password'),

    ('auth.confirm.initial_message', 'Confirming your email...', '正在确认你的邮箱...', 'आपका ईमेल सत्यापित किया जा रहा है...', 'Confirmando tu correo...', 'Confirmant el teu correu...', 'جارٍ تأكيد بريدك الإلكتروني...', 'Confirmation de votre e-mail...', 'Deine E-Mail wird bestaetigt...', 'Confirmando seu e-mail...', 'Подтверждение вашего e-mail...', 'Conferma della tua email...'),
    ('auth.confirm.finishing_signin', 'Finishing sign-in...', '正在完成登录...', 'साइन-इन पूरा किया जा रहा है...', 'Finalizando inicio de sesion...', 'Finalitzant inici de sessio...', 'جارٍ إكمال تسجيل الدخول...', 'Finalisation de la connexion...', 'Anmeldung wird abgeschlossen...', 'Finalizando login...', 'Завершаем вход...', 'Completamento accesso...'),
    ('auth.confirm.failure_message', 'We could not complete your email confirmation.', '无法完成邮箱确认。', 'हम आपका ईमेल सत्यापन पूरा नहीं कर सके।', 'No pudimos completar la confirmacion de tu correo.', 'No hem pogut completar la confirmacio del teu correu.', 'لم نتمكن من إكمال تأكيد بريدك الإلكتروني.', 'Nous n''avons pas pu terminer la confirmation de votre e-mail.', 'Die E-Mail-Bestaetigung konnte nicht abgeschlossen werden.', 'Nao foi possivel concluir a confirmacao do seu e-mail.', 'Не удалось завершить подтверждение e-mail.', 'Non siamo riusciti a completare la conferma della tua email.'),
    ('auth.confirm.title', 'Confirming Access', '正在确认访问', 'पहुंच की पुष्टि हो रही है', 'Confirmando acceso', 'Confirmant acces', 'تأكيد الوصول', 'Confirmation de l''acces', 'Zugriff wird bestaetigt', 'Confirmando acesso', 'Подтверждение доступа', 'Conferma accesso'),

    ('auth.error.page_title', 'Authentication Error | WeddWeb', '身份验证错误 | WeddWeb', 'प्रमाणीकरण त्रुटि | WeddWeb', 'Error de autenticacion | WeddWeb', 'Error d''autenticacio | WeddWeb', 'خطأ في المصادقة | WeddWeb', 'Erreur d''authentification | WeddWeb', 'Authentifizierungsfehler | WeddWeb', 'Erro de autenticacao | WeddWeb', 'Ошибка аутентификации | WeddWeb', 'Errore di autenticazione | WeddWeb'),
    ('auth.error.title', 'Authentication Error', '身份验证错误', 'प्रमाणीकरण त्रुटि', 'Error de autenticacion', 'Error d''autenticacio', 'خطأ في المصادقة', 'Erreur d''authentification', 'Authentifizierungsfehler', 'Erro de autenticacao', 'Ошибка аутентификации', 'Errore di autenticazione'),
    ('auth.error.message', 'We could not complete your authentication. This could be due to an expired link or invalid code.', '我们无法完成身份验证。可能是链接已过期或代码无效。', 'हम प्रमाणीकरण पूरा नहीं कर सके। यह लिंक समाप्त होने या अमान्य कोड के कारण हो सकता है।', 'No pudimos completar tu autenticacion. Puede deberse a un enlace caducado o codigo invalido.', 'No hem pogut completar la teva autenticacio. Pot ser per un enllac caducat o un codi invalid.', 'لم نتمكن من إكمال المصادقة. قد يكون السبب رابط منتهي الصلاحية أو رمز غير صالح.', 'Nous n''avons pas pu terminer votre authentification. Cela peut etre du a un lien expire ou un code invalide.', 'Deine Authentifizierung konnte nicht abgeschlossen werden. Der Link ist moeglicherweise abgelaufen oder der Code ungueltig.', 'Nao foi possivel concluir sua autenticacao. Isso pode ocorrer por link expirado ou codigo invalido.', 'Не удалось завершить аутентификацию. Возможно, ссылка истекла или код недействителен.', 'Non siamo riusciti a completare l''autenticazione. Il link potrebbe essere scaduto o il codice non valido.')
),
expanded AS (
  SELECT "key", 'en'::text AS locale, en AS value FROM seed
  UNION ALL SELECT "key", 'zh', zh FROM seed
  UNION ALL SELECT "key", 'hi', hi FROM seed
  UNION ALL SELECT "key", 'es', es FROM seed
  UNION ALL SELECT "key", 'ca', ca FROM seed
  UNION ALL SELECT "key", 'ar', ar FROM seed
  UNION ALL SELECT "key", 'fr', fr FROM seed
  UNION ALL SELECT "key", 'de', de FROM seed
  UNION ALL SELECT "key", 'pt', pt FROM seed
  UNION ALL SELECT "key", 'ru', ru FROM seed
  UNION ALL SELECT "key", 'it', it FROM seed
)
INSERT INTO public.global_translations ("key", locale, value)
SELECT "key", locale, value
FROM expanded
ON CONFLICT ("key", locale)
DO UPDATE SET value = EXCLUDED.value;

COMMIT;
