BEGIN;

WITH seed("key", en, zh, hi, es, ca, ar, fr, de, pt, ru, it) AS (
  VALUES
    ('pricing.title', 'Plans & Pricing', '套餐与价格', 'प्लान और कीमतें', 'Planes y precios', 'Plans i preus', 'الخطط والأسعار', 'Offres et tarifs', 'Plaene und Preise', 'Planos e precos', 'Тарифы и цены', 'Piani e prezzi'),
    ('pricing.summary', 'Create a beautiful wedding website and share your special day.', '创建精美婚礼网站，分享你的特别日子。', 'एक सुंदर शादी वेबसाइट बनाएं और अपना खास दिन साझा करें।', 'Crea una bonita web de boda y comparte tu dia especial.', 'Crea un web de casament bonic i comparteix el teu dia especial.', 'أنشئ موقع زفاف جميل وشارك يومك المميز.', 'Creez un beau site de mariage et partagez votre jour special.', 'Erstelle eine schoene Hochzeitswebsite und teile euren besonderen Tag.', 'Crie um lindo site de casamento e compartilhe seu dia especial.', 'Создайте красивый свадебный сайт и поделитесь вашим особенным днем.', 'Crea un bellissimo sito di matrimonio e condividi il tuo giorno speciale.'),
    ('pricing.fine_print', 'All prices include applicable taxes where required.', '所有价格均包含适用税费（如法律要求）。', 'जहां लागू हो, सभी कीमतों में कर शामिल हैं।', 'Todos los precios incluyen los impuestos aplicables cuando corresponda.', 'Tots els preus inclouen els impostos aplicables quan sigui necessari.', 'جميع الاسعار تشمل الضرائب المطبقة عند الاقتضاء.', 'Tous les prix incluent les taxes applicables lorsque requis.', 'Alle Preise enthalten anfallende Steuern, falls erforderlich.', 'Todos os precos incluem os impostos aplicaveis quando exigido.', 'Все цены включают применимые налоги, где это требуется.', 'Tutti i prezzi includono le tasse applicabili dove richiesto.'),
    ('pricing.billing.one_time', 'one-time', '一次性', 'एक बार', 'pago unico', 'pagament unic', 'دفعة واحدة', 'paiement unique', 'einmalig', 'pagamento unico', 'единовременно', 'una tantum'),
    ('pricing.billing.monthly', 'monthly', '每月', 'मासिक', 'mensual', 'mensual', 'شهري', 'mensuel', 'monatlich', 'mensal', 'ежемесячно', 'mensile'),
    ('pricing.billing.yearly', 'yearly', '每年', 'वार्षिक', 'anual', 'anual', 'سنوي', 'annuel', 'jaehrlich', 'anual', 'ежегодно', 'annuale'),

    ('billing.header', 'Subscription & Billing', '订阅与账单', 'सदस्यता और बिलिंग', 'Suscripcion y facturacion', 'Subscripcio i facturacio', 'الاشتراك والفوترة', 'Abonnement et facturation', 'Abonnement und Abrechnung', 'Assinatura e faturamento', 'Подписка и биллинг', 'Abbonamento e fatturazione'),
    ('billing.summary', 'Manage your plan, billing information and subscription details.', '管理你的套餐、账单信息和订阅详情。', 'अपनी योजना, बिलिंग जानकारी और सदस्यता विवरण प्रबंधित करें।', 'Gestiona tu plan, informacion de facturacion y detalles de suscripcion.', 'Gestiona el teu pla, la informacio de facturacio i els detalls de subscripcio.', 'ادِر خطتك ومعلومات الفوترة وتفاصيل الاشتراك.', 'Gerez votre offre, vos informations de facturation et les details de votre abonnement.', 'Verwalte deinen Tarif, Rechnungsinformationen und Abonnementdetails.', 'Gerencie seu plano, informacoes de faturamento e detalhes da assinatura.', 'Управляйте планом, платежной информацией и деталями подписки.', 'Gestisci il tuo piano, le informazioni di fatturazione e i dettagli dell''abbonamento.'),
    ('billing.current_plan', 'Current Plan', '当前套餐', 'वर्तमान प्लान', 'Plan actual', 'Pla actual', 'الخطة الحالية', 'Offre actuelle', 'Aktueller Plan', 'Plano atual', 'Текущий план', 'Piano attuale'),
    ('billing.plan_tier_free', 'Free', '免费', 'फ्री', 'Gratis', 'Gratis', 'مجاني', 'Gratuit', 'Kostenlos', 'Gratis', 'Бесплатно', 'Gratis'),
    ('billing.plan_tier_premium', 'Premium', '高级版', 'प्रीमियम', 'Premium', 'Premium', 'مميز', 'Premium', 'Premium', 'Premium', 'Премиум', 'Premium'),
    ('billing.none', 'None', '无', 'कोई नहीं', 'Ninguno', 'Cap', 'لا يوجد', 'Aucun', 'Keine', 'Nenhum', 'Нет', 'Nessuno'),
    ('billing.plan_desc_default', 'Your current plan details are shown below.', '你当前套餐的详情如下。', 'आपकी वर्तमान योजना का विवरण नीचे दिखाया गया है।', 'Los detalles de tu plan actual se muestran a continuacion.', 'Els detalls del teu pla actual es mostren a continuacio.', 'يتم عرض تفاصيل خطتك الحالية ادناه.', 'Les details de votre offre actuelle sont affiches ci-dessous.', 'Die Details deines aktuellen Plans werden unten angezeigt.', 'Os detalhes do seu plano atual sao exibidos abaixo.', 'Детали вашего текущего плана показаны ниже.', 'I dettagli del tuo piano attuale sono mostrati di seguito.'),
    ('billing.features', 'Features', '功能', 'सुविधाएं', 'Funciones', 'Funcionalitats', 'المميزات', 'Fonctionnalites', 'Funktionen', 'Recursos', 'Функции', 'Funzionalita'),
    ('billing.usage', 'Usage', '使用情况', 'उपयोग', 'Uso', 'Us', 'الاستخدام', 'Utilisation', 'Nutzung', 'Uso', 'Использование', 'Utilizzo'),
    ('billing.events', 'Events', '活动', 'कार्यक्रम', 'Eventos', 'Esdeveniments', 'الفعاليات', 'Evenements', 'Events', 'Eventos', 'События', 'Eventi'),
    ('billing.unlimited', 'Unlimited', '无限', 'असीमित', 'Ilimitado', 'Illimitat', 'غير محدود', 'Illimite', 'Unbegrenzt', 'Ilimitado', 'Безлимитно', 'Illimitato'),
    ('billing.subscription', 'Subscription', '订阅', 'सदस्यता', 'Suscripcion', 'Subscripcio', 'الاشتراك', 'Abonnement', 'Abonnement', 'Assinatura', 'Подписка', 'Abbonamento'),
    ('billing.renewal_date', 'Next renewal', '下次续费', 'अगली नवीनीकरण तिथि', 'Proxima renovacion', 'Propera renovacio', 'التجديد القادم', 'Prochain renouvellement', 'Naechste Verlaengerung', 'Proxima renovacao', 'Следующее продление', 'Prossimo rinnovo'),
    ('billing.date_unknown', 'Unknown date', '日期未知', 'अज्ञात तिथि', 'Fecha desconocida', 'Data desconeguda', 'تاريخ غير معروف', 'Date inconnue', 'Unbekanntes Datum', 'Data desconhecida', 'Неизвестная дата', 'Data sconosciuta'),
    ('billing.status', 'Status', '状态', 'स्थिति', 'Estado', 'Estat', 'الحالة', 'Statut', 'Status', 'Status', 'Статус', 'Stato'),
    ('billing.last_invoice', 'Last Invoice', '最近发票', 'पिछला बिल', 'Ultima factura', 'Ultima factura', 'اخر فاتورة', 'Derniere facture', 'Letzte Rechnung', 'Ultima fatura', 'Последний счет', 'Ultima fattura'),
    ('billing.download_receipt', 'Download', '下载', 'डाउनलोड', 'Descargar', 'Descarregar', 'تنزيل', 'Telecharger', 'Herunterladen', 'Baixar', 'Скачать', 'Scarica'),
    ('billing.cta_upgrade', 'Upgrade', '升级', 'अपग्रेड', 'Mejorar plan', 'Millorar pla', 'ترقية', 'Passer en premium', 'Upgrade', 'Fazer upgrade', 'Обновить план', 'Passa a premium'),
    ('billing.cta_pricing', 'See all plans', '查看所有套餐', 'सभी प्लान देखें', 'Ver todos los planes', 'Veure tots els plans', 'عرض جميع الخطط', 'Voir toutes les offres', 'Alle Plaene ansehen', 'Ver todos os planos', 'Посмотреть все тарифы', 'Vedi tutti i piani'),

    ('checkout.info.already_premium', 'You are already premium.', '你已经是高级版用户。', 'आप पहले से ही प्रीमियम पर हैं।', 'Ya eres premium.', 'Ja ets premium.', 'انت بالفعل على الخطة المميزة.', 'Vous etes deja premium.', 'Du bist bereits Premium.', 'Voce ja e premium.', 'У вас уже премиум.', 'Hai gia premium.'),
    ('checkout.info.downgrade_not_available', 'Downgrading from your current paid plan to Free is not available yet. Your current plan remains active.', '目前暂不支持从付费套餐降级到免费套餐。你当前套餐将保持有效。', 'आपकी मौजूदा भुगतान योजना से फ्री पर डाउनग्रेड अभी उपलब्ध नहीं है। आपकी वर्तमान योजना सक्रिय रहेगी।', 'Bajar de tu plan de pago actual al plan Gratis aun no esta disponible. Tu plan actual seguira activo.', 'Baixar del teu pla de pagament actual al pla Gratis encara no esta disponible. El teu pla actual continuara actiu.', 'الرجوع من خطتك المدفوعة الحالية الى الخطة المجانية غير متاح بعد. ستبقى خطتك الحالية نشطة.', 'Le passage de votre offre payante actuelle vers l''offre gratuite n''est pas encore disponible. Votre offre actuelle reste active.', 'Ein Downgrade von deinem aktuellen Bezahlplan auf Free ist derzeit nicht verfuegbar. Dein aktueller Plan bleibt aktiv.', 'O downgrade do seu plano pago atual para o plano Gratuito ainda nao esta disponivel. Seu plano atual permanecera ativo.', 'Понижение с вашего текущего платного плана до бесплатного пока недоступно. Ваш текущий план останется активным.', 'Il downgrade dal tuo piano a pagamento attuale al piano Gratuito non e ancora disponibile. Il tuo piano attuale rimane attivo.'),
    ('checkout.error.unauthorized', 'Please sign in to continue.', '请先登录以继续。', 'जारी रखने के लिए कृपया साइन इन करें।', 'Inicia sesion para continuar.', 'Inicia sessio per continuar.', 'يرجى تسجيل الدخول للمتابعة.', 'Veuillez vous connecter pour continuer.', 'Bitte melde dich an, um fortzufahren.', 'Faca login para continuar.', 'Пожалуйста, войдите, чтобы продолжить.', 'Accedi per continuare.'),
    ('checkout.error.invalid_request', 'Invalid checkout request.', '无效的结账请求。', 'अमान्य चेकआउट अनुरोध।', 'Solicitud de pago no valida.', 'Sol-licitud de pagament no valida.', 'طلب دفع غير صالح.', 'Requete de paiement invalide.', 'Ungueltige Checkout-Anfrage.', 'Solicitacao de pagamento invalida.', 'Недопустимый запрос на оплату.', 'Richiesta di pagamento non valida.'),
    ('checkout.error.server', 'Server error. Please try again.', '服务器错误。请重试。', 'सर्वर त्रुटि। कृपया फिर से प्रयास करें।', 'Error del servidor. Intentalo de nuevo.', 'Error del servidor. Torna-ho a provar.', 'خطا في الخادم. يرجى المحاولة مرة اخرى.', 'Erreur serveur. Veuillez reessayer.', 'Serverfehler. Bitte versuche es erneut.', 'Erro no servidor. Tente novamente.', 'Ошибка сервера. Попробуйте еще раз.', 'Errore del server. Riprova.'),
    ('checkout.error.create_session', 'Failed to create checkout session', '无法创建结账会话', 'चेकआउट सेशन बनाया नहीं जा सका', 'No se pudo crear la sesion de pago', 'No s''ha pogut crear la sessio de pagament', 'تعذر انشاء جلسة الدفع', 'Impossible de creer la session de paiement', 'Checkout-Sitzung konnte nicht erstellt werden', 'Falha ao criar sessao de pagamento', 'Не удалось создать сессию оплаты', 'Impossibile creare la sessione di pagamento'),
    ('checkout.error.unexpected', 'An unexpected error occurred', '发生了意外错误', 'एक अनपेक्षित त्रुटि हुई', 'Ocurrio un error inesperado', 'S''ha produït un error inesperat', 'حدث خطا غير متوقع', 'Une erreur inattendue est survenue', 'Ein unerwarteter Fehler ist aufgetreten', 'Ocorreu um erro inesperado', 'Произошла непредвиденная ошибка', 'Si e verificato un errore imprevisto'),
    ('checkout.error.plan_change_not_available', 'Plan Change Not Available', '套餐变更不可用', 'प्लान परिवर्तन उपलब्ध नहीं है', 'Cambio de plan no disponible', 'Canvi de pla no disponible', 'تغيير الخطة غير متاح', 'Changement de forfait indisponible', 'Planwechsel nicht verfuegbar', 'Alteracao de plano indisponivel', 'Смена плана недоступна', 'Cambio piano non disponibile'),
    ('checkout.error.title', 'Checkout Error', '结账错误', 'चेकआउट त्रुटि', 'Error de pago', 'Error de pagament', 'خطا في الدفع', 'Erreur de paiement', 'Checkout-Fehler', 'Erro no pagamento', 'Ошибка оплаты', 'Errore di pagamento'),
    ('checkout.action.back_to_pricing', 'Back to Pricing', '返回价格页', 'मूल्य निर्धारण पर वापस जाएं', 'Volver a precios', 'Tornar a preus', 'العودة الى الاسعار', 'Retour aux tarifs', 'Zurueck zur Preisuebersicht', 'Voltar para precos', 'Назад к тарифам', 'Torna ai prezzi'),
    ('checkout.status.payment_success_title', 'Payment Successful!', '支付成功！', 'भुगतान सफल!', 'Pago completado con exito', 'Pagament completat amb exit', 'تم الدفع بنجاح!', 'Paiement reussi !', 'Zahlung erfolgreich!', 'Pagamento realizado com sucesso!', 'Оплата прошла успешно!', 'Pagamento riuscito!'),
    ('checkout.status.processing_title', 'Processing...', '处理中...', 'प्रोसेस किया जा रहा है...', 'Procesando...', 'Processant...', 'جار المعالجة...', 'Traitement en cours...', 'Wird verarbeitet...', 'Processando...', 'Обработка...', 'Elaborazione in corso...'),
    ('checkout.status.payment_success_desc', 'Your payment has been processed successfully. Redirecting to your site...', '你的支付已成功处理。正在跳转到你的网站...', 'आपका भुगतान सफलतापूर्वक संसाधित हो गया है। आपकी साइट पर रीडायरेक्ट किया जा रहा है...', 'Tu pago se ha procesado correctamente. Redirigiendo a tu sitio...', 'El teu pagament s''ha processat correctament. Redirigint al teu lloc web...', 'تمت معالجة دفعتك بنجاح. جاري اعادة توجيهك الى موقعك...', 'Votre paiement a ete traite avec succes. Redirection vers votre site...', 'Deine Zahlung wurde erfolgreich verarbeitet. Weiterleitung zu deiner Website...', 'Seu pagamento foi processado com sucesso. Redirecionando para seu site...', 'Ваш платеж успешно обработан. Перенаправляем на ваш сайт...', 'Il tuo pagamento e stato elaborato con successo. Reindirizzamento al tuo sito...'),
    ('checkout.status.setting_up_free', 'Setting up your free plan...', '正在设置你的免费套餐...', 'आपकी फ्री योजना सेट की जा रही है...', 'Configurando tu plan gratuito...', 'Configurant el teu pla gratuit...', 'جار اعداد خطتك المجانية...', 'Configuration de votre offre gratuite...', 'Dein kostenloser Plan wird eingerichtet...', 'Configurando seu plano gratuito...', 'Настраиваем ваш бесплатный план...', 'Configurazione del tuo piano gratuito...'),
    ('checkout.status.preparing_checkout', 'Preparing secure checkout...', '正在准备安全结账...', 'सुरक्षित चेकआउट तैयार किया जा रहा है...', 'Preparando un pago seguro...', 'Preparant un pagament segur...', 'جار تجهيز دفع امن...', 'Preparation du paiement securise...', 'Sicherer Checkout wird vorbereitet...', 'Preparando checkout seguro...', 'Подготавливаем безопасную оплату...', 'Preparazione del checkout sicuro...'),
    ('checkout.status.wait', 'Please wait, this may take a moment.', '请稍候，这可能需要一点时间。', 'कृपया प्रतीक्षा करें, इसमें कुछ समय लग सकता है।', 'Espera un momento, esto puede tardar un poco.', 'Si us plau espera, aixo pot trigar uns instants.', 'يرجى الانتظار، قد يستغرق هذا لحظة.', 'Veuillez patienter, cela peut prendre un instant.', 'Bitte warten, das kann einen Moment dauern.', 'Aguarde, isso pode levar um momento.', 'Пожалуйста, подождите, это может занять немного времени.', 'Attendi, potrebbe richiedere qualche istante.'),
    ('checkout.badge.secure_by_stripe', 'Secure payment processing by Stripe', '由 Stripe 提供安全支付处理', 'Stripe द्वारा सुरक्षित भुगतान प्रोसेसिंग', 'Procesamiento de pago seguro con Stripe', 'Processament de pagament segur amb Stripe', 'معالجة دفع امنة عبر Stripe', 'Paiement securise via Stripe', 'Sichere Zahlungsabwicklung mit Stripe', 'Processamento de pagamento seguro pela Stripe', 'Безопасная обработка платежей через Stripe', 'Elaborazione pagamenti sicura con Stripe')
),
expanded AS (
  SELECT "key", 'en'::text AS locale, en AS value FROM seed
  UNION ALL SELECT "key", 'zh', zh FROM seed
  UNION ALL SELECT "key", 'hi', hi FROM seed
  UNION ALL SELECT "key", 'es', es FROM seed
  UNION ALL SELECT "key", 'ca', ca FROM seed
  UNION ALL SELECT "key", 'ar', ar FROM seed
  UNION ALL SELECT "key", 'fr', fr FROM seed
  UNION ALL SELECT "key", 'de', de FROM seed
  UNION ALL SELECT "key", 'pt', pt FROM seed
  UNION ALL SELECT "key", 'ru', ru FROM seed
  UNION ALL SELECT "key", 'it', it FROM seed
)
INSERT INTO public.global_translations_builder ("key", locale, value)
SELECT "key", locale, value
FROM expanded
ON CONFLICT ("key", locale)
DO UPDATE SET value = EXCLUDED.value;

COMMIT;
