-- Upsert for pricing.limit.* keys in all 11 supported languages for public.global_translations_marketing
INSERT INTO public.global_translations_marketing (key, locale, value, updated_at)
VALUES
  -- images
  ('pricing.limit.images', 'en', 'Images', NOW()),
  ('pricing.limit.images', 'es', 'Imágenes', NOW()),
  ('pricing.limit.images', 'ca', 'Imatges', NOW()),
  ('pricing.limit.images', 'zh', '图片', NOW()),
  ('pricing.limit.images', 'hi', 'छवियाँ', NOW()),
  ('pricing.limit.images', 'ar', 'صور', NOW()),
  ('pricing.limit.images', 'fr', 'Images', NOW()),
  ('pricing.limit.images', 'de', 'Bilder', NOW()),
  ('pricing.limit.images', 'pt', 'Imagens', NOW()),
  ('pricing.limit.images', 'ru', 'Изображения', NOW()),
  ('pricing.limit.images', 'it', 'Immagini', NOW()),
  -- accommodations
  ('pricing.limit.accommodations', 'en', 'Accommodations', NOW()),
  ('pricing.limit.accommodations', 'es', 'Alojamientos', NOW()),
  ('pricing.limit.accommodations', 'ca', 'Allotjaments', NOW()),
  ('pricing.limit.accommodations', 'zh', '住宿', NOW()),
  ('pricing.limit.accommodations', 'hi', 'आवास', NOW()),
  ('pricing.limit.accommodations', 'ar', 'إقامات', NOW()),
  ('pricing.limit.accommodations', 'fr', 'Hébergements', NOW()),
  ('pricing.limit.accommodations', 'de', 'Unterkünfte', NOW()),
  ('pricing.limit.accommodations', 'pt', 'Acomodações', NOW()),
  ('pricing.limit.accommodations', 'ru', 'Жильё', NOW()),
  ('pricing.limit.accommodations', 'it', 'Alloggi', NOW()),
  -- events
  ('pricing.limit.events', 'en', 'Events', NOW()),
  ('pricing.limit.events', 'es', 'Eventos', NOW()),
  ('pricing.limit.events', 'ca', 'Esdeveniments', NOW()),
  ('pricing.limit.events', 'zh', '活动', NOW()),
  ('pricing.limit.events', 'hi', 'इवेंट्स', NOW()),
  ('pricing.limit.events', 'ar', 'فعاليات', NOW()),
  ('pricing.limit.events', 'fr', 'Événements', NOW()),
  ('pricing.limit.events', 'de', 'Veranstaltungen', NOW()),
  ('pricing.limit.events', 'pt', 'Eventos', NOW()),
  ('pricing.limit.events', 'ru', 'События', NOW()),
  ('pricing.limit.events', 'it', 'Eventi', NOW()),
  -- whatToSee
  ('pricing.limit.whatToSee', 'en', 'What to See', NOW()),
  ('pricing.limit.whatToSee', 'es', 'Qué ver', NOW()),
  ('pricing.limit.whatToSee', 'ca', 'Què veure', NOW()),
  ('pricing.limit.whatToSee', 'zh', '景点', NOW()),
  ('pricing.limit.whatToSee', 'hi', 'देखने योग्य', NOW()),
  ('pricing.limit.whatToSee', 'ar', 'أماكن للزيارة', NOW()),
  ('pricing.limit.whatToSee', 'fr', 'À voir', NOW()),
  ('pricing.limit.whatToSee', 'de', 'Sehenswertes', NOW()),
  ('pricing.limit.whatToSee', 'pt', 'O que ver', NOW()),
  ('pricing.limit.whatToSee', 'ru', 'Что посмотреть', NOW()),
  ('pricing.limit.whatToSee', 'it', 'Cosa vedere', NOW()),
  -- weddingGiftMethods
  ('pricing.limit.weddingGiftMethods', 'en', 'Gift Methods', NOW()),
  ('pricing.limit.weddingGiftMethods', 'es', 'Métodos de regalo', NOW()),
  ('pricing.limit.weddingGiftMethods', 'ca', 'Mètodes de regal', NOW()),
  ('pricing.limit.weddingGiftMethods', 'zh', '礼物方式', NOW()),
  ('pricing.limit.weddingGiftMethods', 'hi', 'उपहार विधियाँ', NOW()),
  ('pricing.limit.weddingGiftMethods', 'ar', 'طرق الهدايا', NOW()),
  ('pricing.limit.weddingGiftMethods', 'fr', 'Méthodes de cadeau', NOW()),
  ('pricing.limit.weddingGiftMethods', 'de', 'Geschenkmöglichkeiten', NOW()),
  ('pricing.limit.weddingGiftMethods', 'pt', 'Métodos de presente', NOW()),
  ('pricing.limit.weddingGiftMethods', 'ru', 'Способы подарков', NOW()),
  ('pricing.limit.weddingGiftMethods', 'it', 'Metodi regalo', NOW()),
  -- languages
  ('pricing.limit.languages', 'en', 'Languages', NOW()),
  ('pricing.limit.languages', 'es', 'Idiomas', NOW()),
  ('pricing.limit.languages', 'ca', 'Idiomes', NOW()),
  ('pricing.limit.languages', 'zh', '语言', NOW()),
  ('pricing.limit.languages', 'hi', 'भाषाएँ', NOW()),
  ('pricing.limit.languages', 'ar', 'اللغات', NOW()),
  ('pricing.limit.languages', 'fr', 'Langues', NOW()),
  ('pricing.limit.languages', 'de', 'Sprachen', NOW()),
  ('pricing.limit.languages', 'pt', 'Idiomas', NOW()),
  ('pricing.limit.languages', 'ru', 'Языки', NOW()),
  ('pricing.limit.languages', 'it', 'Lingue', NOW()),
  -- customDomains
  ('pricing.limit.customDomains', 'en', 'Custom Domains', NOW()),
  ('pricing.limit.customDomains', 'es', 'Dominios personalizados', NOW()),
  ('pricing.limit.customDomains', 'ca', 'Dominis personalitzats', NOW()),
  ('pricing.limit.customDomains', 'zh', '自定义域名', NOW()),
  ('pricing.limit.customDomains', 'hi', 'कस्टम डोमेन', NOW()),
  ('pricing.limit.customDomains', 'ar', 'نطاقات مخصصة', NOW()),
  ('pricing.limit.customDomains', 'fr', 'Domaines personnalisés', NOW()),
  ('pricing.limit.customDomains', 'de', 'Eigene Domains', NOW()),
  ('pricing.limit.customDomains', 'pt', 'Domínios personalizados', NOW()),
  ('pricing.limit.customDomains', 'ru', 'Пользовательские домены', NOW()),
  ('pricing.limit.customDomains', 'it', 'Domini personalizzati', NOW())
ON CONFLICT (key, locale)
DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
